spring:
    config:
        activate:
            on-profile: development
myproperties:
    threadPool: 50
    email: something@development.site
---
spring:
    config:
        activate:
            on-profile: production
myproperties:
    threadPool: 1000
    email: something@production.site
