spring:
    config:
        activate:
            on-profile: development
myproperties:
    threadPool: 50
    email: something@development.site
    servers:
        - www.abc.dev.com
        - www.xyz.dev.com
---
spring:
    config:
        activate:
            on-profile: production
myproperties:
    threadPool: 1000
    email: something@production.site
    servers:
        - www.abc.com
        - www.xyz.com
